-- MySQL Script generated by MySQL Workbench
-- sáb 07 sep 2024 18:42:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mesas` (
  `nnumero_mesa` INT(4) NOT NULL AUTO_INCREMENT,
  `ncantidad_asientos` INT(4) NULL,
  `dispinibilidad` VARCHAR(12) NULL,
  PRIMARY KEY (`nnumero_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `nnumero_reserva` INT(4) NOT NULL AUTO_INCREMENT,
  `ccodigo_verificacion` VARCHAR(6) NULL,
  `dfecha` DATE NULL,
  `dhora` TIME NULL,
  PRIMARY KEY (`nnumero_reserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `nid_persona` INT(4) NOT NULL,
  `nombre` VARCHAR(25) NULL,
  `apellido` VARCHAR(25) NULL,
  `dfecha_nacimiento` DATE NULL,
  PRIMARY KEY (`nid_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `nid_rol` INT(4) NOT NULL,
  `rol` VARCHAR(20) NULL,
  PRIMARY KEY (`nid_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `nid_usuario` INT(4) NOT NULL,
  `cnombre_usuario` VARCHAR(30) NULL,
  `cemail` VARCHAR(64) NULL,
  `cpass` VARCHAR(255) NULL,
  `rela_nid_persona` INT(4) NULL,
  `rela_nid_rol` INT(4) NULL,
  PRIMARY KEY (`nid_usuario`),
  INDEX `fk_usuarios_personas_idx` (`rela_nid_persona` ASC) VISIBLE,
  INDEX `fk_usuarios_roles1_idx` (`rela_nid_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_personas`
    FOREIGN KEY (`rela_nid_persona`)
    REFERENCES `mydb`.`personas` (`nid_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`rela_nid_rol`)
    REFERENCES `mydb`.`roles` (`nid_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_reservas` (
  `nnumero_detalle` INT(4) NOT NULL,
  `rela_nnumero_reserva` INT(4) NULL,
  `rela_nid_usuario` INT(4) NULL,
  `rela_nnumero_mesa` INT(4) NULL,
  `ncantidad_personas` INT(4) NULL,
  PRIMARY KEY (`nnumero_detalle`),
  INDEX `fk_detalle_reservas_usuarios1_idx` (`rela_nid_usuario` ASC) VISIBLE,
  INDEX `fk_detalle_reservas_reservas1_idx` (`rela_nnumero_reserva` ASC) VISIBLE,
  INDEX `fk_detalle_reservas_mesas1_idx` (`rela_nnumero_mesa` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_reservas_usuarios1`
    FOREIGN KEY (`rela_nid_usuario`)
    REFERENCES `mydb`.`usuarios` (`nid_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_reservas_reservas1`
    FOREIGN KEY (`rela_nnumero_reserva`)
    REFERENCES `mydb`.`reservas` (`nnumero_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_reservas_mesas1`
    FOREIGN KEY (`rela_nnumero_mesa`)
    REFERENCES `mydb`.`mesas` (`nnumero_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleados` (
  `nnumero_empleados` INT(4) NOT NULL,
  `ccuit` VARCHAR(11) NULL,
  `daño_ingreso` DATE NULL,
  `cdni` VARCHAR(8) NULL,
  `rela_nid_persona` INT(4) NULL,
  PRIMARY KEY (`nnumero_empleados`),
  INDEX `fk_empleados_personas1_idx` (`rela_nid_persona` ASC) VISIBLE,
  CONSTRAINT `fk_empleados_personas1`
    FOREIGN KEY (`rela_nid_persona`)
    REFERENCES `mydb`.`personas` (`nid_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
